### ISSUE TITLE
Data layer and GUI Component systems

### ISSUE THREAD

**Issue by gedw99** [chasefleming/elem-go#70]
Does anyone have any preference for the top and bottom layers ? 

Bottom being the Data Access Layer. Examples being: Sqlc, Ent, Pocketable, etc 
- Since elem.go is object level and not string baed, we get strong typing.

Top being the reusable GUI Components. Examples being Material Design Web,  DaisyUI, etc.
- Its a fair bot of work and in the htmx style we need pure html based system.

**Comment by gedw99** [comment]
Seen a few devs using daisy ui with htmx. Daisy is impressive too if you play with it on line

**Comment by chasefleming** [comment]
Re the UI point: there are actually a a couple opportunities to extend or for packages built on top of `elem-go`:

## Existing Libraries

I had been thinking that since Tailwind is so popular and its mostly CSS classes it could be cool with `elem-go` to have a subpackage or for a community member to make a package for Tailwind that has constants like the `attrs`, `styles`, or `htmx` subpackes. For example:

```go
const (
    // Text Colors
    TextWhite = "text-white"
    TextBlack = "text-black"
    // ...

    // Background Colors
    BgBlue500 = "bg-blue-500"
    BgRed500  = "bg-red-500"
    // ...

    // Spacing
    P2 = "p-2"
    P4 = "p-4"
    // ...

    // Layout
    Flex     = "flex"
    Grid     = "grid"
    // ...

    // Borders
    Border     = "border"
    Border2    = "border-2"
    // ...

    // Others...
)
```

You technically don't need this to start building since you can just apply the classes as string but this would definitely be more convenient and align with the type-safe patterns of the library. Since it wouldn't be built with your project as a subpackage if you didn't use it, then it might not hurt to add to this library. I'm just weary to start adding a long list of subpackages when maybe it's better they are community maintained.

## New Libraries

There is also opportunity for people to build new component libraries on top of `elem-go`. If someone wanted to start one it could be really cool. Think about components made like this:

```go
func CreateCard(title, content string) elem.Node {
	return elem.Div(
		attrs.Props{attrs.Class: "card"},
		elem.H2(nil, elem.Text(title)),
		elem.P(nil, elem.Text(content)),
	)
}
```

Or like this:

```go
type CardData struct {
	Title   string
	Content string
}

func Card(data CardData) elem.Node {
	return elem.Div(attrs.Props{attrs.Class: "card"},
		elem.H2(nil, elem.Text(data.Title)),
		elem.P(nil, elem.Text(data.Content)),
	)
}
```

It's also a pattern people could use in their own apps to have a component system and open source later if they think others will find it useful.
